language: java
jdk:
- oraclejdk8
sudo: false
before_deploy: mvn clean verify
deploy:
  skip_cleanup: true
  provider: lambda
  access_key_id:
    secure: XB6TF+3xGdUIhjiBoaJSrhmNKxD6Kmy9eVIRtRkuqja5IpTtoBCCDp5kpEa7L8hYY3DqANCtzWJpQor5Feq6f73vN0NvItUXI34PLe6+W9z5dssmnm0fPyumh4m+pWVlai0X2f+ihJ/6ASYsYTt5/IGCrFvX6vJdh62zuj7OI79+BrR3osA3GR2EcYif2aeKOezlaFNEl74XJ74EMgj51UBPIN+MFqB6R4phAJ0Ob31HDM/9b3uYG2RfqgcyrMtB8AkoEn9fUTVhzlRB6DkgmLTmEbILFNay3YIuw19gBTfq2/nTT87yLIWIXOtcVwBb6h+LyVx67o3ikK9GRf5k16YR8mMNEfhMrw7V+KR2HKZUoiR4BYL7Pumyp60LF2zNh0AzAn8wMeSdyorFR/ErCcHRhzGatOLbRNUPLEi06p8OqW4bFIKxnaQWACI2OR3FBryoV8I7DJpYQdzmF2INGWpciGfWd4Gn5eFqnmHLWXRAvVe0gRaXAxZa6UnNi3CMnAJWxiLzCnpazQvo2myYuUrVa/tZqPCbJEvfRdpaLl7jTXdZdxfmFpJFLOE08x7XGVl3ecIJ+TuB6Jz+MkCOyzvlwoLBTE5dOc6BMzls+6ZziQXX/2y0vQEM531N3fmFQn/oq0EVCMuRVd8VhQel5jqSOKPHsEkPyvOobjgR/DY=
  secret_access_key:
    secure: Pzj5LuJF90MbXvAGr0smaVYZ3eX68vhdIrZ3l0dV1vgl7HiGavK0RBFtRWUx/NDaGiCz/sQf/cok7/djfw2nURK5lXC0VLP87ejkdvr4yijMDFFpNsMIJPBXJiLxEUhxXtOb9Qrazb3L1nBNxkRLcmwd9aVM/a2iANGTXZj7F7lGcrIebsUJE9QXVfkSmFA3VSNYoxZ2GkGVabdpKd0oJCePD7SNy+VKYrtSuCUZv/Ar9UTcopWYu8foy+O8nJVc4y55DiKabqrs77Aj8YxjRpunjo8OD5c7GYTll+deYzWZy5QpSxYcHQKJ+rHLvinQ+qJASm/PqxCRsZcVJcEmQy5sLQcK+tvfJB2lys4QziYXLp+l8GDVPBX4dSkoBrzRaNkeEaYhBViq9O714cO5qPlJ3Wid6kI0cmkEOO4VFKHHy6dItxJnrxsfJdNekVJktGtfZLWV18/HOEwTpdeT12SDwuz3QvdDJ0zR0rf0eBCpPLHtQKBK7oy/MSbgIKjhy/3etmS2bePtvnuNjTQLjO6WyKpd4SvlHrz84MnobNUK8+rjDY/cYOiL7Yy81LkQOecC8brNyjaJ1Opd2XHl2sbbSEacfQj5zcXr1Xs0cKfhjkWlIf6PPzNEho6YN6/RFq7nmk3+RbX9vtP40bbEpQ/1J2sNUJedfebG2Xif9ek=
  region: us-east-1
  function_name:
    develop: Bridge-EX-Scheduler-dev
    uat: Bridge-EX-Scheduler-uat
    prod: Bridge-EX-Scheduler-prod
  role:
    develop: arn:aws:iam::649232250620:role/Bridge-EX-Scheduler-Dev
    uat: arn:aws:iam::649232250620:role/Bridge-EX-Scheduler-Uat
    prod: arn:aws:iam::649232250620:role/Bridge-EX-Scheduler-Prod
  handler_name: org.sagebionetworks.bridge.exporter.scheduler.SchedulerLauncher::launch
  zip-file: target/Bridge-EX-Scheduler-2.0.jar
